/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.project.test;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
     int a = 10;
     int b = 5;
      
      Mul m = new Mul();
     System.out.println(m.mul(a, b));
      
    }
}
